// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.5.1 with parameter "target=ts,keep_empty_files=true"
// @generated from file common/ledger.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/ledger.proto.
 */
export const file_common_ledger: GenFile = /*@__PURE__*/
  fileDesc("ChNjb21tb24vbGVkZ2VyLnByb3RvEgZjb21tb24imwEKDkJsb2NrY2hhaW5JbmZvEg4KBmhlaWdodBgBIAEoBBIYChBjdXJyZW50QmxvY2tIYXNoGAIgASgMEhkKEXByZXZpb3VzQmxvY2tIYXNoGAMgASgMEkQKGWJvb3RzdHJhcHBpbmdTbmFwc2hvdEluZm8YBCABKAsyIS5jb21tb24uQm9vdHN0cmFwcGluZ1NuYXBzaG90SW5mbyI4ChlCb290c3RyYXBwaW5nU25hcHNob3RJbmZvEhsKE2xhc3RCbG9ja0luU25hcHNob3QYASABKARCVgokb3JnLmh5cGVybGVkZ2VyLmZhYnJpYy5wcm90b3MuY29tbW9uWi5naXRodWIuY29tL2h5cGVybGVkZ2VyL2ZhYnJpYy1wcm90b3MtZ28vY29tbW9uYgZwcm90bzM");

/**
 * Contains information about the blockchain ledger such as height, current
 * block hash, and previous block hash.
 *
 * @generated from message common.BlockchainInfo
 */
export type BlockchainInfo = Message<"common.BlockchainInfo"> & {
  /**
   * @generated from field: uint64 height = 1;
   */
  height: bigint;

  /**
   * @generated from field: bytes currentBlockHash = 2;
   */
  currentBlockHash: Uint8Array;

  /**
   * @generated from field: bytes previousBlockHash = 3;
   */
  previousBlockHash: Uint8Array;

  /**
   * Specifies bootstrapping snapshot info if the channel is bootstrapped from a snapshot.
   * It is nil if the channel is not bootstrapped from a snapshot.
   *
   * @generated from field: common.BootstrappingSnapshotInfo bootstrappingSnapshotInfo = 4;
   */
  bootstrappingSnapshotInfo?: BootstrappingSnapshotInfo;
};

/**
 * Describes the message common.BlockchainInfo.
 * Use `create(BlockchainInfoSchema)` to create a new message.
 */
export const BlockchainInfoSchema: GenMessage<BlockchainInfo> = /*@__PURE__*/
  messageDesc(file_common_ledger, 0);

/**
 * Contains information for the bootstrapping snapshot.
 *
 * @generated from message common.BootstrappingSnapshotInfo
 */
export type BootstrappingSnapshotInfo = Message<"common.BootstrappingSnapshotInfo"> & {
  /**
   * @generated from field: uint64 lastBlockInSnapshot = 1;
   */
  lastBlockInSnapshot: bigint;
};

/**
 * Describes the message common.BootstrappingSnapshotInfo.
 * Use `create(BootstrappingSnapshotInfoSchema)` to create a new message.
 */
export const BootstrappingSnapshotInfoSchema: GenMessage<BootstrappingSnapshotInfo> = /*@__PURE__*/
  messageDesc(file_common_ledger, 1);

