// Copyright the Hyperledger Fabric contributors. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.5.1 with parameter "target=ts,keep_empty_files=true"
// @generated from file orderer/smartbft/configuration.proto (package orderer.smartbft, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file orderer/smartbft/configuration.proto.
 */
export const file_orderer_smartbft_configuration: GenFile = /*@__PURE__*/
  fileDesc("CiRvcmRlcmVyL3NtYXJ0YmZ0L2NvbmZpZ3VyYXRpb24ucHJvdG8SEG9yZGVyZXIuc21hcnRiZnQiqQUKB09wdGlvbnMSHwoXcmVxdWVzdF9iYXRjaF9tYXhfY291bnQYASABKAQSHwoXcmVxdWVzdF9iYXRjaF9tYXhfYnl0ZXMYAiABKAQSIgoacmVxdWVzdF9iYXRjaF9tYXhfaW50ZXJ2YWwYAyABKAkSJAocaW5jb21pbmdfbWVzc2FnZV9idWZmZXJfc2l6ZRgEIAEoBBIZChFyZXF1ZXN0X3Bvb2xfc2l6ZRgFIAEoBBIfChdyZXF1ZXN0X2ZvcndhcmRfdGltZW91dBgGIAEoCRIgChhyZXF1ZXN0X2NvbXBsYWluX3RpbWVvdXQYByABKAkSIwobcmVxdWVzdF9hdXRvX3JlbW92ZV90aW1lb3V0GAggASgJEhkKEXJlcXVlc3RfbWF4X2J5dGVzGAkgASgEEiMKG3ZpZXdfY2hhbmdlX3Jlc2VuZF9pbnRlcnZhbBgKIAEoCRIbChN2aWV3X2NoYW5nZV90aW1lb3V0GAsgASgJEiAKGGxlYWRlcl9oZWFydGJlYXRfdGltZW91dBgMIAEoCRIeChZsZWFkZXJfaGVhcnRiZWF0X2NvdW50GA0gASgEEhcKD2NvbGxlY3RfdGltZW91dBgOIAEoCRIVCg1zeW5jX29uX3N0YXJ0GA8gASgIEhwKFHNwZWVkX3VwX3ZpZXdfY2hhbmdlGBAgASgIEjsKD2xlYWRlcl9yb3RhdGlvbhgRIAEoDjIiLm9yZGVyZXIuc21hcnRiZnQuT3B0aW9ucy5Sb3RhdGlvbhIcChRkZWNpc2lvbnNfcGVyX2xlYWRlchgSIAEoBCJHCghSb3RhdGlvbhIYChRST1RBVElPTl9VTlNQRUNJRklFRBAAEhAKDFJPVEFUSU9OX09GRhABEg8KC1JPVEFUSU9OX09OEAJCagoub3JnLmh5cGVybGVkZ2VyLmZhYnJpYy5wcm90b3Mub3JkZXJlci5zbWFydGJmdFo4Z2l0aHViLmNvbS9oeXBlcmxlZGdlci9mYWJyaWMtcHJvdG9zLWdvL29yZGVyZXIvc21hcnRiZnRiBnByb3RvMw");

/**
 * Options to be specified for all the smartbft nodes. These can be modified on a
 * per-channel basis.
 *
 * @generated from message orderer.smartbft.Options
 */
export type Options = Message<"orderer.smartbft.Options"> & {
  /**
   * @generated from field: uint64 request_batch_max_count = 1;
   */
  requestBatchMaxCount: bigint;

  /**
   * @generated from field: uint64 request_batch_max_bytes = 2;
   */
  requestBatchMaxBytes: bigint;

  /**
   * @generated from field: string request_batch_max_interval = 3;
   */
  requestBatchMaxInterval: string;

  /**
   * @generated from field: uint64 incoming_message_buffer_size = 4;
   */
  incomingMessageBufferSize: bigint;

  /**
   * @generated from field: uint64 request_pool_size = 5;
   */
  requestPoolSize: bigint;

  /**
   * @generated from field: string request_forward_timeout = 6;
   */
  requestForwardTimeout: string;

  /**
   * @generated from field: string request_complain_timeout = 7;
   */
  requestComplainTimeout: string;

  /**
   * @generated from field: string request_auto_remove_timeout = 8;
   */
  requestAutoRemoveTimeout: string;

  /**
   * @generated from field: uint64 request_max_bytes = 9;
   */
  requestMaxBytes: bigint;

  /**
   * @generated from field: string view_change_resend_interval = 10;
   */
  viewChangeResendInterval: string;

  /**
   * @generated from field: string view_change_timeout = 11;
   */
  viewChangeTimeout: string;

  /**
   * @generated from field: string leader_heartbeat_timeout = 12;
   */
  leaderHeartbeatTimeout: string;

  /**
   * @generated from field: uint64 leader_heartbeat_count = 13;
   */
  leaderHeartbeatCount: bigint;

  /**
   * @generated from field: string collect_timeout = 14;
   */
  collectTimeout: string;

  /**
   * @generated from field: bool sync_on_start = 15;
   */
  syncOnStart: boolean;

  /**
   * @generated from field: bool speed_up_view_change = 16;
   */
  speedUpViewChange: boolean;

  /**
   * @generated from field: orderer.smartbft.Options.Rotation leader_rotation = 17;
   */
  leaderRotation: Options_Rotation;

  /**
   * @generated from field: uint64 decisions_per_leader = 18;
   */
  decisionsPerLeader: bigint;
};

/**
 * Describes the message orderer.smartbft.Options.
 * Use `create(OptionsSchema)` to create a new message.
 */
export const OptionsSchema: GenMessage<Options> = /*@__PURE__*/
  messageDesc(file_orderer_smartbft_configuration, 0);

/**
 * @generated from enum orderer.smartbft.Options.Rotation
 */
export enum Options_Rotation {
  /**
   * @generated from enum value: ROTATION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ROTATION_OFF = 1;
   */
  OFF = 1,

  /**
   * @generated from enum value: ROTATION_ON = 2;
   */
  ON = 2,
}

/**
 * Describes the enum orderer.smartbft.Options.Rotation.
 */
export const Options_RotationSchema: GenEnum<Options_Rotation> = /*@__PURE__*/
  enumDesc(file_orderer_smartbft_configuration, 0, 0);

